name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn    
      - name: yarn install, lint and build
        run: | 
          yarn install --immutable
          yarn build
          yarn buildlib
